---
title: "Cleaning the data"
author: "Rena Cohen"
date: "11/10/2020"
output: html_document
---

```{r}
library(tidyverse)
library(readr)
library(janitor)
library(readxl)
View(masks)
```

```{r}
# Here is the initial NYT dataset

masks <- read_csv("raw_data_masks/mask-use-by-county.csv") %>%
  
  # changing column names to lowercase
  
  janitor::clean_names() %>%
  mutate(countyfp = as.character(countyfp))

# Here is population data

pop <- read_csv("raw_data_masks/PopulationEstimates(1).csv") %>%
  
  # Relevant variables are county code, state, rural urban continuum, and population
  
  select("FIPStxt", "State", "Rural-urban_Continuum Code_2013", "POP_ESTIMATE_2019") %>%
  rename("countyfp" = "FIPStxt", "state" = "State", "ru_continuum" = "Rural-urban_Continuum Code_2013", "pop_2019" = "POP_ESTIMATE_2019") %>%
  mutate(countyfp = ifelse(nchar(countyfp) == 4, paste0("0", countyfp), countyfp)) %>%
  mutate(countyfp = as.character(countyfp))



# Moving on to education data

education <- read_csv("raw_data_masks/Education.csv") %>%
  select("FIPS Code", "Percent of adults with less than a high school diploma, 2014-18",
         "Percent of adults with a high school diploma only, 2014-18", 
         "Percent of adults completing some college or associate's degree, 2014-18", 
         "Percent of adults with a bachelor's degree or higher, 2014-18") %>%
  rename("countyfp" = "FIPS Code",
         "pct_less_than_hs" = "Percent of adults with less than a high school diploma, 2014-18",
         "pct_hs" = "Percent of adults with a high school diploma only, 2014-18",
         "pct_some_college" = "Percent of adults completing some college or associate's degree, 2014-18",
         "pct_college" = "Percent of adults with a bachelor's degree or higher, 2014-18")  %>%
  mutate(countyfp = as.character(countyfp)) %>%
  mutate(countyfp = ifelse(nchar(countyfp) == 4, paste0("0", countyfp), countyfp))
  
View(voting)

# 2020 Presidential elections

voting <- read_csv("raw_data_masks/2020_US_County_Level_Presidential_Results.csv") %>%
  select(county_fips, county_name, per_gop, state_name) %>%
  rename("countyfp" = "county_fips", "percent_gop" = "per_gop") %>%
  mutate(countyfp = as.character(countyfp))

View(voting)

View(voting)

# Mask mandates

mask_mandates <- read_excel("raw_data_masks/earliestpolicy_08042020.xlsx") %>%
  select("1067", "...5") %>%
  rename("county" = "1067", "mandate" = "...5") %>%
  
  # adding leading 0's to county codes without them, since excel got rid of them
  
  mutate(countyfp = ifelse(nchar(county) == 4, paste0("0", county), county)) %>%
  
  # creating a dummy variable coded 1 if there is a county mandate
  
  mutate(county_mandate = ifelse(is.na(mandate), 0, 1)) %>%
  select(county_mandate, countyfp) %>%
  mutate(countyfp = as.character(countyfp))

# NYT Covid data

covid <- read_csv("raw_data_masks/us-counties.csv") %>%

# I'm going to select the row with the number of cases and deaths at the beginning of 
# the NYT mask survey, which was July 2nd
  
  filter(date == "2020-07-02") %>%
  select(fips, cases, deaths, county) %>%
  rename("countyfp" = fips) %>%
  mutate(countyfp = as.character(countyfp))

# Poverty rate data

poverty <- read_csv("raw_data_masks/PovertyEstimates.csv") %>%
  select("FIPStxt", "PCTPOVALL_2018") %>%
  rename("countyfp" = "FIPStxt", "pct_poverty" = "PCTPOVALL_2018") %>%
  mutate(countyfp = as.character(countyfp)) %>%
  mutate(countyfp = ifelse(nchar(countyfp) == 4, paste0("0", countyfp), countyfp))
  
# Population raw data 

older_people <-  read_csv("raw_data_masks/cc-est2019-agesex-02.csv") %>%
  janitor::clean_names() %>%
  
  # Feature engineering to get the FIPS code by combining state and county
  
  unite("countyfp", state:county, sep = "") %>%
  
  # We want only the most recent data (year = 12) 
  
  filter(year == 12) %>%
  
  # Creating a variable that's the percent seniors in a county
  
  mutate(pct_senior = age65plus_tot/popestimate) %>%
  mutate(countyfp = as.character(countyfp))

total_pop <- read_csv("raw_data_masks/cc-est2019-alldata-02.csv") %>%
  janitor::clean_names() %>%
  
  # Feature engineering to get the FIPS code by combining state and county
  
  unite("countyfp", state:county, sep = "") %>%
  
  # We want only the most recent data (year = 12) 
  
  filter(year == 12) %>%
  
  group_by(countyfp) %>%
  
  # Age group 0 represents characteristics of the population at large
  
  filter(agegrp == 0) %>%

# Making race and gender into percentages rather than raw counts
  mutate(pct_female = tot_female/tot_pop) %>%
  mutate(pct_black = (ba_male + ba_female)/tot_pop) %>%
  mutate(pct_native = (ia_male + ia_female)/tot_pop) %>%
  mutate(pct_asian = (aa_male + aa_female)/tot_pop) %>%
  mutate(pct_hispanic = (h_male + h_female)/tot_pop) %>%
  select(countyfp, pct_female, pct_black, tot_pop, pct_native, pct_asian, pct_hispanic) %>%
  mutate(countyfp = as.character(countyfp))



```

```{r}
# Time for the big join!! Let's hope it works

# Since the nyt dataset has our y variables, I will left join with the 
# county codes in that

# Countyfp has to be the same type of column in everything. I'll make it a 
# character

join_1 <- left_join(x = masks, y = pop, by = "countyfp")
View()

join_2 <- left_join(x = join_1, y = education, by = "countyfp")
join_3 <- left_join(x = join_2, y = voting, by = "countyfp")
join_4 <- left_join(x = join_3, y = mask_mandates, by = "countyfp")
join_5 <- left_join(x = join_4, y = covid, by = "countyfp")
join_6 <- left_join(x = join_5, y = poverty, by = "countyfp")
join_7 <- left_join(x = join_6, y = all_pop, by = "countyfp")

# Finally, just cleaning up our last join a little bit

states_mandate = c("CA", "CT", "DE", "DC", "HI",
                   "IL", "KS", "LA", "ME", "MA",
                   "MD", "MI", "NV", "NJ", "NM",
                   "NY", "NC", "OH", "OR", "PA", 
                   "RI", "VA", "WA", "WV")

states_dem_gov = c("CA", "CO", "CT", "DE", "HI",
                   "IL", "KS", "KY", "LA", "ME",
                   "MI", "MN", "MT", "NV", "NJ",
                   "NM", "NY", "NC", "OR", "PA",
                   "RI", "VA", "WA", "WI")

clean_data = join_7 %>%
  select(-county) %>%
  
  # adding a column for state mask mandates
  
  mutate(state_mandate = ifelse(state %in% states_mandate, 1, 0)) %>%
  
  # adding a column for governor political party (coded 1 if democrat)
  
  mutate(dem_governor = ifelse(state %in% states_dem_gov, 1, 0)) %>%
  
  rename("pct_trump" = "percent_gop") %>%
  
  # reordering the columns for ease of working with
  
  select(countyfp, county_name, state, everything()) %>%
  
  # Adding the weighted average column Kevin suggested
  # 1 = always, 0.75 = frequently, 0.5 = sometimes, 0.25 = rarely, 0 = never
  
  mutate(pct_mask = always + 0.75*frequently + 0.5*sometimes + 
           0.25*rarely)

saveRDS(clean_data, file = "clean_data.rds")
```


```{r}
# Here are more edits post Kevin

# Grabbing the number of cases for two weeks after the end of the survey (2020_07_28)
# Jk this data only goes up to July 27th, so I'll grab that instead


covid_27 <- read_csv("raw_data_masks/us-counties.csv") %>%
  filter(date == "2020-07-27") %>%
  select(fips, cases, deaths) %>%
  rename("countyfp" = fips, "cases_27" = cases, "deaths_27" = deaths) %>%
  mutate(countyfp = as.character(countyfp))

# I'm also going to select the dates that was when the survey ended, July 14th

covid_14 <- read_csv("raw_data_masks/us-counties.csv") %>%

# I'm going to select the row with the number of cases and deaths 2 weeks after the end of
# the NYT mask survey, which was July 28th
  
  filter(date == "2020-07-14") %>%
  select(fips, cases, deaths) %>%
  rename("countyfp" = fips, "cases_14" = cases, "deaths_14" = deaths) %>%
  mutate(countyfp = as.character(countyfp))

View(voting)

# But I will add the 2016 county level election results in case we want
# to use those instead of 2020

voting_2016 <- read_csv("raw_data_masks/county_level_election.csv") %>%
  select(fipscode,trump, density) %>%
  rename("countyfp" = fipscode, "pct_trump_2016" = trump) %>%
  mutate(countyfp = as.character(countyfp)) %>%
  mutate(countyfp = ifelse(nchar(countyfp) == 4, paste0("0", countyfp), countyfp))
  
View(voting_2016)
data_2 <- readRDS("clean_data.rds") %>%
  # Adding the weighted average column Kevin suggested
  # 1 = always, 0.75 = frequently, 0.5 = sometimes, 0.25 = rarely, 0 = never
  
  mutate(pct_mask = always + 0.75*frequently + 0.5*sometimes + 
           0.25*rarely) %>%
  rename("pct_trump_2020" = pct_trump, "cases_02" = cases, "deaths_02" = deaths)
  
# Rejoining with our new data

join_8 <- left_join(x = data_2, y = covid_14, by = "countyfp")
join_9 <- left_join(x = join_8, y = covid_27, by = "countyfp")
join_10 <- left_join(x = join_9, y = voting_2016, by = "countyfp")

View(join_10)

clean_data_2 <- join_10 %>%
  # Making growth rate columns for model spread growth of cases. case_growth_1 will be
  # growth between the start and end of the survey, case_growth_2 is between the end of 
  # the survey and the next two weeks
  
  mutate(case_growth_1 = cases_14/cases_02) %>%
  mutate(case_growth_2 = cases_27/cases_14) %>%
  
  # Making sure all the percentages are on the same scale
  # I will make them on the 100's scale, such that an increase of 
  # 1 is equal to an increase of one percent
  
  mutate(pct_mask = 100*pct_mask) %>%
  mutate(always = 100*always) %>%
  mutate(frequently = 100*frequently) %>%
  mutate(sometimes = 100*sometimes) %>%
  mutate(rarely = 100*rarely) %>%
  mutate(never = 100*never) %>%
  mutate(case_growth_1 = 100*case_growth_1) %>%
  mutate(case_growth2 = 100*case_growth_2) %>%
  mutate(pct_female = 100*pct_female) %>%
  mutate(pct_black = 100*pct_black) %>%
  mutate(pct_native = 100*pct_native) %>%
  mutate(pct_hispanic = 100*pct_hispanic) %>%
  mutate(pct_asian = 100*pct_asian) %>%
  mutate(pct_seniors = 100*pct_seniors) %>%
  mutate(pct_trump_2020 = 100*pct_trump_2020) %>%
  
  # rearranging columns again
  
  select(countyfp, county_name, state, pct_mask, always, frequently,
         sometimes, rarely, never, cases_02, deaths_02, cases_14, deaths_14,
         cases_27, deaths_27, case_growth_1, case_growth_2, pop_2019, ru_continuum,
         density, pct_less_than_hs, pct_hs, pct_some_college, pct_college, pct_poverty,
         pct_female, pct_black, pct_native, pct_hispanic, pct_asian, pct_seniors, 
         pct_trump_2016, pct_trump_2020, dem_governor, state_mandate, county_mandate) 


```


```{r}

summary(lm(always~(.-countyfp - county_name - never -state - always - rarely - sometimes - tot_pop - frequently), data = clean_data))

summary(lm(always~ru_continuum, data = clean_data))

plot(never~log(cases), data = clean_data)

```

